name: news_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  animated_splash_screen: ^1.3.0
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  get: ^4.6.6
  http: ^1.2.1
  iconsax: ^0.0.8
  lottie: ^3.1.0
  smooth_page_indicator: ^1.1.0
  video_player: ^2.8.3
  webview_flutter: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/animation/
    - assets/images/business.jpg
    - assets/images/entertainment.jpg
    - assets/images/health.jpg
    - assets/images/science.jpg
    - assets/images/sports.jpg
    - assets/images/technology.jpg

